davinci:
  is_enabled: False
  source:
    year: 2011
    energy: 3500
    direction: "Up"
    strippingNumber: "21r1"

cutflow:
  muon_PT: 25000

histogram:
  nbins: 100

  ZMM:
    from: 0
    to: 140000
