name: "canvas_sum_Rapidity"
title: "Lepton Sum Rapidity Distribution"
outputFilename: "../intermediate-data/histograms/muon_Rapidity_sum.root" 
outputChartFilename: "../../results/muon_Rapidity_sum.png"


histograms:
  - name: "SumRapidity"
    title: "Sum Rapidity"
    expression: "muon_sum_LorentzVector.Rapidity()"
    nbinsx: 100
    xlow: 1.0
    xup: 5.5
    color: 416   # kGreen


stack:
  name: "Sum_Rapidity_stack"
  title: "Lepton Sum Rapidity"
  xaxisTitle: "Rapidity"
  yaxisTitle: "Frequency"
