name: "canvas_rapidity"
title: "Muon Rapidity Distribution"
outputFilename: "../../results/muon_Rapidity.png" 


histograms:
  - name: "LeadingRapidity"
    title: "Rapidity Leading"
    expression: "muon1_PT > muon2_PT ? muon1_LorentzVector.Rapidity() : muon2_LorentzVector.Rapidity()"
    nbinsx: 100
    xlow: 1.0
    xup: 5.5
    color: 416   # kGreen
    
  - name: "SubleadingRapidity"
    title: "Rapidity Subleading"
    expression: "muon1_PT > muon2_PT ? muon2_LorentzVector.Rapidity() : muon1_LorentzVector.Rapidity()"
    nbinsx: 100
    xlow: 1.0
    xup: 5.5
    color: 600   # kBlue

stack:
  name: "Rapidity_stack"
  title: "Muon Rapidity Distribution"
  xaxisTitle: "Rapidity"
  yaxisTitle: "Frequency"
